Dev (#29)
* try to use vendor in ci

* add node and pnpm install checks

* revert to app config struct and add read mutex

* implement changes as per #26 and move traefik setup to bootstrap

* fix traefik-bootstrap setup

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -56,6 +56,7 @@ source ".envrc"
 readonly SPEC="openapi.yaml"
 readonly PROTO_DIR="internal/pb"
 readonly MIGRATIONS_DIR="db/migrations"
+readonly CERTIFICATES_DIR="certificates"
 readonly REPOS="internal/repos"
 readonly PG_REPO="$REPOS/postgresql"
 readonly PG_REPO_GEN="$PG_REPO/gen"
@@ -88,7 +89,7 @@ xlog() {
     color="$MAGENTA"
   fi
 
-  if [[ "${FUNCNAME[1]%%.*}" == "check" ]]; then
+  if [[ "${FUNCNAME[1]}" =~ ^.*(check\.bin|install\.bin).* ]]; then
     max_len=100
   fi
 
@@ -96,7 +97,7 @@ xlog() {
     fname="${fname:0:$max_len}…"
   fi
 
-  local fn=$(printf "%*s |\n" $((max_fname_log_len + 1)) "$fname")
+  local fn=$(printf "%*s |\n" $((max_len + 1)) "$fname")
   sed -ue "s/^/${color}$fname >${OFF} /"
 
   # return ${PIPESTATUS[0]}
@@ -107,12 +108,14 @@ xlog() {
 # > >(one) 2> >(two) are background processes so it will break our parallel code.
 xerr() {
   local fname="${FUNCNAME[1]#*.}"
+  local max_len=$MAX_FNAME_LOG_LEN
+
   [[ "$CMD" = "$fname" ]] && cat && return
-  if [[ ${#fname} -gt $max_fname_log_len ]]; then
-    fname="${fname:0:$max_fname_log_len}…"
+  if [[ ${#fname} -gt $max_len ]]; then
+    fname="${fname:0:$max_len}…"
   fi
 
-  local fn=$(printf "%*s |\n" $((max_fname_log_len + 1)) "$fname")
+  local fn=$(printf "%*s |\n" $((max_len + 1)) "$fname")
   sed -ue "s/^/${RED}$fname >${OFF} /" >&2
 
   # return ${PIPESTATUS[0]}
@@ -128,9 +131,12 @@ kill_descendants() {
 # Check dependencies and fetch required tools.
 x.bootstrap() {
   { { {
+    git submodule update --init --recursive
     x.check-build-deps
     x.install-tools
-    x.fetch.swagger-ui
+    x.setup.swagger-ui
+    traefik_dir="$HOME/traefik-bootstrap"
+    confirm "Do you want to setup and run traefik (install dir: $traefik_dir)?" && x.setup.traefik "$traefik_dir"
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -159,7 +165,7 @@ x.install-tools() {
 }
 
 # Fetch latest Swagger UI bundle.
-x.fetch.swagger-ui() {
+x.setup.swagger-ui() {
   { { {
     local name="$(curl --silent "https://api.github.com/repos/swagger-api/swagger-ui/releases/latest" | jq -r ".. .tag_name? // empty")"
     curl -fsSL "github.com/swagger-api/swagger-ui/archive/refs/tags/$name.tar.gz" -o swagger-ui.tar.gz
@@ -771,7 +777,7 @@ x.run-prod() {
   cd frontend && pnpm run generate && cd - >/dev/null
   x.gen
 
-  DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker-compose \
+  DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker compose \
     --project-name "$PROJECT_PREFIX"_"$env" \
     -f docker-compose."$env".yml \
     --env-file ".env.$env" \
@@ -829,6 +835,17 @@ x.search-stopship() {
       exit 1
     fi
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+# Runs a traefik container with predefined configuration.
+x.setup.traefik() {
+  git clone --depth=1 https://github.com/danicc097/traefik-bootstrap.git "$1"
+  docker network create traefik-net || true
+  mkdir -p "$1"/traefik/certificates
+  cp $CERTIFICATES_DIR/* "$1"/traefik/certificates
+  cd "$1"
+  ./compose-up
+  cd - >/dev/null
 }
 
 ########################## migrations ##########################
@@ -1277,6 +1294,50 @@ install.bin.direnv() {
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
+check.bin.pnpm() {
+  { { {
+    local vers
+    vers=$(pnpm --version)
+    minver=7
+    { [[ "$vers" =~ [v]?([0-9]+)[\.]{1} ]] &&
+      ((BASH_REMATCH[1] >= minver)) &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.pnpm() {
+  { { {
+    sudo npm i -g pnpm@7.6.0
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.node() {
+  { { {
+    local vers
+    vers=$(node --version)
+    minver=16
+    { [[ "$vers" =~ [v]?([0-9]+)[\.]{1} ]] &&
+      ((BASH_REMATCH[1] >= minver)) &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.node() {
+  { { {
+    sudo npm i -g node@7.6.0
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
 check.bin.sponge() {
   { { {
     { [[ $(command -v sponge) =~ /sponge$ ]] &&
@@ -1319,7 +1380,7 @@ install.bin.mkcert() {
     wget https://github.com/FiloSottile/mkcert/releases/download/v"$VERSION"/mkcert-v"$VERSION"-linux-amd64 -O mkcert
     chmod +x mkcert
     mv mkcert ./bin/tools/
-    cd certificates || exit
+    cd $CERTIFICATES_DIR || exit
     echo "Setting up local certificates"
     mkcert --cert-file localhost.pem --key-file localhost-key.pem localhost "*.dev.localhost" "*.ci.localhost" "*.prod.localhost" 127.0.0.1 ::1 host.docker.internal
     cd ..
@@ -1342,7 +1403,7 @@ run_shared_services() {
   docker network create traefik-net 2>/dev/null || true
 
   cd docker
-  DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker-compose \
+  DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker compose \
     -p "$PROJECT_PREFIX" \
     -f docker-compose.shared.yml \
     -f docker-compose.oidc.yml \
