backup restore test

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -45,9 +45,10 @@ readonly MAX_FNAME_LOG_LEN=13
 
 GEN_POSTGRES_DB="gen_db"
 
-# determines if gen cache should be restore at program exit, i.e. failed commands. 0|1
+# determines whether gen cache should be restored at program exit, i.e. failed commands.
 # cache folder must be cleaned at exit if true.
-need_backup_restore=0
+# only restores if true.
+declare need_backup_restore
 # stores the first executing function of xsetup.backup to track if caching gen is already running,
 # to allow for nested xsetup.backup and cache-cleanup inside multiple functions.
 xsetup_backup_gen_caller=""
@@ -145,14 +146,14 @@ xsetup.backup() {
   git checkout -b "$backup_branch" &>/dev/null
   git stash apply "stash^{/$backup_stash_name}" &>/dev/null
 
-  need_backup_restore=1
+  need_backup_restore=true # unless
 }
 
 xsetup.backup.cleanup() {
   # only accept gen if the main function that backed it up in the first place
   # finishes successfully, i.e. this very function was called
   if [[ "$xsetup_backup_gen_caller" = "${FUNCNAME[1]}" ]]; then
-    need_backup_restore=0
+    need_backup_restore=false
   fi
 }
 
@@ -2204,14 +2205,14 @@ exit-cleanup() {
   [[ "$exit_cleanup_calls" -gt 0 ]] && return
   ((exit_cleanup_calls++)) || true
 
-  if [[ $need_backup_restore = 1 ]]; then
+  if [[ $need_backup_restore = true ]]; then
     test -z $X_NO_BACKUP && xsetup.backup.restore
     # IMPORTANT: if any command failed always restore gen cache, regardless of flags passed.
     gen-cache.restore
   fi
 
   # shared cleanup regardless of gen success
-  git checkout "$CURRENT_BRANCH" &>/dev/null || err "Could not checkout $CURRENT_BRANCH branch"
+  git checkout "$CURRENT_BRANCH" || err "Could not checkout $CURRENT_BRANCH branch"
   rm -f backup-gen-stash-dummy.txt
   git branch -D "$backup_branch" &>/dev/null || true
 
