remove openapi generator

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -80,7 +80,6 @@ x.check-build-deps() {
     check.protoc || { ((fails++)) && true; }
     check.bash || { ((fails++)) && true; }
     check.go || { ((fails++)) && true; }
-    check.java || { ((fails++)) && true; }
     check.curl || { ((fails++)) && true; }
     check.docker || { ((fails++)) && true; }
     check.docker-compose || { ((fails++)) && true; }
@@ -97,7 +96,6 @@ x.bootstrap() {
   { { {
     x.check-build-deps
     x.install-tools
-    x.fetch.openapi-gen
     x.fetch.swagger-ui
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
@@ -116,21 +114,13 @@ x.install-tools() {
     go install mvdan.cc/gofumpt@latest
     go install github.com/danicc097/air@latest
     go install github.com/danicc097/xo@latest
+    go install github.com/mikefarah/yq/v4@v4.27.2
 
     go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
     go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@v0.2.0
     go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
 
     GO111MODULE=off go get -u github.com/maxbrunsfeld/counterfeiter
-  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-}
-
-# Fetch openapi-generator jar file.
-x.fetch.openapi-gen() {
-  { { {
-    local url="https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/$GENVERS/openapi-generator-cli-$GENVERS.jar"
-    echo "$url > openapi-generator-cli.jar"
-    curl -L "$url" -o openapi-generator-cli.jar
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -144,25 +134,6 @@ x.fetch.swagger-ui() {
     mkdir -p internal/static/swagger-ui
     mv swagger-ui/* internal/static/swagger-ui/
     rm -r swagger-ui
-  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-}
-
-# Run openapi generator for testdata.
-# jar won't output properly if absolute paths are passed from subdir.
-x.gen.tests-api() {
-  { { {
-    local testdata="$BIN_DIR/../internal/postgen/testdata/openapi_generator"
-    local test_dirs=$(find "$testdata" -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
-
-    cache=".generate-tests-api.cache"
-    for test_dir in $test_dirs; do
-      generate_api \
-        "$cache" \
-        "$test_dir" \
-        "$testdata/$test_dir/openapi.yaml" \
-        "$testdata/$test_dir/internal" \
-        "$BIN_DIR/../internal/go-gin-server-templates"
-    done
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -182,24 +153,19 @@ x.pregen() {
       mapfile -t db_enums < <(dockerdb psql -qtAX -d $GEN_POSTGRES_DB -c "SELECT unnest(enum_range(NULL::\"$enum\"));" 2>/dev/null)
 
       [[ ${#db_enums[@]} -gt 0 ]] || { echo "Enum '$enum' not found in database. Skipping" >&2 && continue; }
-      for i in ${!db_enums[@]}; do
-        # FIXME not supported by openapi-generator. Should be thinking of moving on to deepmap's or roll our own
-        [[ ${db_enums[$i]} == *" "* ]] && err "Enums with spaces currently not supported: '${db_enums[$i]}'"
-        db_enums[$i]="\"${db_enums[$i]}\""
-      done
-      enums=$(printf ",%s" "${db_enums[@]}")
+      enums=$(printf ",\"%s\"" "${db_enums[@]}")
       enums="[${enums:1}]"
       echo "Replacing enum '$enum' in $SPEC with: $enums"
       enums=$enums yq e ".$path.enum = env(enums)" -i $SPEC
     done
 
     echo "Applying PascalCase to operation IDs in $SPEC"
-    for opId in $(yq e ".. | select(has(\"operationId\")).operationId" $SPEC); do
-      newopId="$(to_pascal $opId)"
-      paths=$(opId=$opId yq e ".. | select(has(\"operationId\") and .operationId == env(opId)) | (path)" $SPEC)
+    for opid in $(yq e ".. | select(has(\"operationId\")).operationId" $SPEC); do
+      new_opid="$(to_pascal $opid)"
+      paths=$(opid=$opid yq e ".. | select(has(\"operationId\") and .operationId == env(opid)) | (path)" $SPEC)
       mapfile paths <<<$paths
       escaped_path="$(join_yq_paths paths)"
-      newopId=$newopId yq e ".$escaped_path.operationId = env(newopId)" -i $SPEC
+      new_opid=$new_opid yq e ".$escaped_path.operationId = env(new_opid)" -i $SPEC
     done
 
     # go build -o pregen "$PWD"/cmd/pregen/main.go
@@ -297,7 +263,7 @@ x.gen.proto() {
       --go_out=internal/pb/. \
       --go-grpc_opt=M$filename=$import_path,paths=import \
       --go_opt=M$filename=$import_path,paths=import \
-      internal/python-ml-app-protos/tfidf/v1/service.proto
+      internal/python-ml-app-protos/tfidf/v1/service.proto || err "Failed proto generation"
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -312,8 +278,6 @@ x.gen() {
     cache=".generate.cache"
 
     x.pregen
-
-    generate_api "$cache" "internal" "$SPEC" "$OPENAPI_GEN_OUT_DIR" "$TEMPLATE_DIR"
 
     rm -rf $PG_REPO/gen
 
@@ -336,7 +300,6 @@ x.gen() {
     done
 
     x.postgen "$cache"
-    _pids+=($!)
 
     # delay since it depends on generated output
     x.gen.counterfeiter "$cache"
@@ -397,7 +360,6 @@ x.test.backend-setup() {
     run_shared_services up -d --remove-orphans
     x.gen
     drop_and_recreate_db "postgres_test"
-    x.gen.tests-api
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -694,55 +656,6 @@ x.e2e.run() {
 
 ########################## openapi ##########################
 
-# Validates the project's OpenAPI specification or `spec`.
-# Args: [spec]
-x.validate() {
-  # quite unreliable. e.g. ignored examples inexistent ref.
-  # prefer built in kin-openapi validation
-  java -jar openapi-generator-cli.jar validate -i "${1:-$SPEC}"
-}
-
-# Wrapper for openapi-generator with sane output modifications.
-# Args: spec out tpl
-x.openapi-generator() {
-  { { {
-    local spec="$1"
-    local gen_out_dir="$2"
-    local template_dir="$3"
-
-    [[ -z $spec ]] && err "openapi-generator: spec required"
-    [[ -z $gen_out_dir ]] && err "openapi-generator: out dir required"
-    [[ -z $template_dir ]] && err "openapi-generator: template dir required"
-    echo "Generating API from $spec"
-    echo "Generation directory: $gen_out_dir"
-    echo "Template override directory: $template_dir"
-
-    rm -rf "$gen_out_dir/gen"
-    # debug has a very small overhead compared to the >1s required per spec
-    java -jar "$BIN_DIR"/../openapi-generator-cli.jar generate \
-      -g go-gin-server \
-      -i "$spec" \
-      -o "$gen_out_dir" \
-      -t "$template_dir" \
-      --additional-properties=packageName=openapi,apiPath=gen,hideGenerationTimestamp=true \
-      --enable-post-process-file >/dev/null
-    # --global-property=debugModels,debugOperations >debug-openapi.log #>/dev/null \
-
-    mkdir -p "$gen_out_dir"/gen/models
-    mkdir -p "$gen_out_dir"/rest
-    mkdir -p "$gen_out_dir"/services
-
-    mv "$gen_out_dir"/gen/routers.go "$gen_out_dir"/rest/routers.gen.go
-
-    {
-      mv "$gen_out_dir"/gen/model_*.go "$gen_out_dir"/gen/models 2>/dev/null
-      goimports -w "$gen_out_dir"/gen/models
-    } || echo "No model files found. Skipping"
-
-    rm -rf "$gen_out_dir/api"
-  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-}
-
 # Run a diff against the previous OpenAPI spec in the main branch.
 # Can also be used to generate changelogs when upgrading major versions.
 x.diff-oas() {
@@ -804,38 +717,6 @@ x.gen.xo() {
       -e "*.created_at" \
       -e "*.updated_at" || err "Failed xo generation"
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-}
-
-generate_api() {
-  cache="$1"
-  prefix="$2"
-  spec="$3"
-  gen_out_dir="$4"
-  template_dir="$5"
-
-  invalid_cache=false
-
-  if [[ $force_regen -eq 1 ]]; then
-    rm -rf "$cache"
-  fi
-
-  mkdir -p "$cache"
-
-  if ! md5sum -c "$cache/$prefix-go-gin-server-templates.md5" >/dev/null; then
-    invalid_cache=true
-    md5sum "$BIN_DIR"/../internal/go-gin-server-templates/* >"$cache/$prefix-go-gin-server-templates.md5"
-  fi
-  if ! md5sum -c "$cache/$prefix-openapi.md5" >/dev/null; then
-    invalid_cache=true
-    md5sum "$BIN_DIR"/../"$SPEC" >"$cache/$prefix-openapi.md5"
-  fi
-
-  if [[ $invalid_cache == true ]]; then
-    x.openapi-generator \
-      "$spec" \
-      "$gen_out_dir" \
-      "$template_dir"
-  fi
 }
 
 usage() {
