good state to build tools

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -729,10 +729,15 @@ x.gen.client-server() {
     echo "Running generation"
     paths=".openapi.paths.yaml"
 
-    local structs=()
-    mapfile -t structs < <(ast-parser find-structs --exclude-generics --public-only "internal/rest/models.go")
-    struct_names_list=$(join_by "," ${structs[*]})
+    local all_types=()
+    go-utils.find_all_types all_types "internal/rest/models.go"
+    all_types_list=$(join_by "," ${all_types[*]})
+    local models_structs=()
 
+    mapfile -t models_structs < <(ast-parser find-structs --exclude-generics --public-only "internal/rest/models.go")
+
+    struct_names_list=$(join_by "," ${all_types_list[*]})
+    echo $all_types_list
     # hack to get separate types generation
     sed "s/\$ref: '\#\//\$ref: '$SPEC_PATH\#\//g" $SPEC_PATH >"$paths"
     # yq e 'del(.components)' -i "$paths" # dont delete since recent oapi-codegen does some checks even if we are not generating types
@@ -743,13 +748,13 @@ x.gen.client-server() {
     # (should enforce it by verifying import list in the package via ast-parser Imports map[string]*packages.Package):
     # `ast-parser verify-no-import --imports "$GOMOD_PKG/internal/models" internal/rest` errors out if found
     oapi-codegen --config internal/models/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed types generation"
-    oapi-codegen --config internal/rest/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed rest types generation"
-    ast-parser find-redeclared --delete internal/rest/models.go # for duplicates in rest
-    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --structs "$struct_names_list" "$paths" || err "Failed server generation"
+    # oapi-codegen --config internal/rest/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed rest types generation"
+    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --types "$struct_names_list" "$paths" || err "Failed server generation"
     oapi-codegen --config internal/rest/oapi-codegen-test-client.yaml "$SPEC_PATH" || err "Failed client generation"
     oapi-codegen --config internal/client/oapi-codegen-client.yaml "$SPEC_PATH" || err "Failed client generation"
 
-    codegen implement-server # based on oapi gen
+    ast-parser find-redeclared --delete internal/rest/models.go # for duplicates in rest
+    codegen implement-server                                    # based on oapi gen
 
     files=$(find "internal/rest/" -name "*.go")
     goimports -w $files
@@ -949,7 +954,7 @@ x.gen.build-tools() {
     out_dir=$BUILD_DIR
 
     mkdir -p $out_dir
-    for cmd in jet oapi-codegen codegen; do
+    for cmd in jet oapi-codegen codegen ast-parser; do
       echo "Building $cmd..."
       { go build -o $out_dir/$cmd cmd/$cmd/main.go || [[ -n "$X_IGNORE_BUILD_ERRORS" ]]; } &
     done
