Dev (#270)
* envrc update

* update

* update tests

* act on bare html element click

* better warning store and form generation

* remove old form warnings once new data arrives

* remove warnings consistently

* fixed fast refresh

* update config

* update

* orval override axios error

* remove useless db error json response append

* error callout example

* update gen

* update

* update work item tag

* update

* update tests

* refactor fixtures

* fix orval broken query gen

* precommit

* update

* update

* update tests

* use require errors

* update

* update example openapi query parameters

* update

* go test watch with cache opts

* notes

* working sse test server - test multiple topics on that

* example sse

* subscribe to topics individiually and handle client disconnection consistently

* proper client disconnection handling

* send message only to subscribed clients

* update

* dont use default in select

* entr notes

* subscription channel map per topic

* publish

* refacotr

* simplify event server

* refactor sse

* readme update

* request id middelware

* request id notes

* add events to main app

* TODO should have server type gen override for schema fields or arrays

* update event test

* fix golang ci lint

* event server accesible and update tests

* update

* event dispatcher dummy

* gin mode data race fix

* showcase event queue

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -659,7 +659,12 @@ clean_yq_array() {
 }
 
 go_test() {
-  APP_ENV="$X_ENV" go test ${go_test_flags[@]} $@
+  local cache_opt="-count=1"
+  cache_all "$GEN_CACHE/go-test.md5" .env.$X_ENV db/ >/dev/null && cache_opt=""
+
+  set -x
+  APP_ENV="$X_ENV" go test ${go_test_flags[@]} $cache_opt $@
+  set +x
 }
 
 # Run post-generation scripts in the internal package.
@@ -834,8 +839,12 @@ x.gen.client-server() {
 
     local all_types=()
     mapfile -t all_types < <(ast-parser find-types --exclude-generics --public-only "$REST_MODELS")
-
     types_list=$(join_by "," ${all_types[*]})
+
+    # TODO should work for references that are not used in, e.g. Topics
+    mapfile -t server_types < <(yq e '.components.schemas[] | select(.x-use-server-type == true) | key' $SPEC_PATH)
+    server_types_list=$(join_by "," ${server_types[*]})
+
     # hack to get separate types generation
     sed "s/\$ref: '\#\//\$ref: '$SPEC_PATH\#\//g" $SPEC_PATH >"$paths_file"
 
@@ -846,11 +855,22 @@ x.gen.client-server() {
     # models from rest/models.go (source of generated spec schemas)
     # and not the generated ones to avoid (a lot of) unnecessary conversions.
     oapi-codegen --config internal/models/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed types generation" &
-    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --types "$types_list" "$paths_file" || err "Failed server generation" &
+    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --server-types "$server_types_list" --types "$types_list" "$paths_file" || err "Failed server generation" &
     oapi-codegen --config internal/rest/oapi-codegen-test-client.yaml "$SPEC_PATH" || err "Failed client generation" &
     oapi-codegen --config internal/client/oapi-codegen-client.yaml "$SPEC_PATH" || err "Failed client generation" &
 
     wait_without_error
+
+    # local configs=(
+    #   "internal/models/oapi-codegen-types.yaml"
+    #   "internal/rest/oapi-codegen-server.yaml"
+    #   "internal/rest/oapi-codegen-test-client.yaml"
+    #   "internal/client/oapi-codegen-client.yaml"
+    # )
+    # for config in ${configs[@]}; do
+    #   local file_path=$(yq e ".output" $config)
+    #   sed -Ei 's/union([[:space:]])json.RawMessage/Union\1json.RawMessage/g' "$file_path"
+    # done
 
     ast-parser find-redeclared --delete "$REST_MODELS" # for duplicates in rest. depends on oapi-codegen output
     codegen implement-server                           # depends on oapi-codegen output
@@ -1103,7 +1123,7 @@ x.lint.go() {
     -name "*.go")
   goimports -w $files || err "Linting failed"
   gofumpt -w $files || err "Linting failed"
-  golangci-lint run --config=.golangci.yml --allow-parallel-runners --fix &>/dev/null || true
+  golangci-lint run --config=.golangci.yml --allow-parallel-runners --fast --fix &>/dev/null || true
 }
 
 exhaustruct_lint() {
@@ -1220,36 +1240,30 @@ x.test.backend() {
     # done per test suite database automatically
     # yes y 2>/dev/null | POSTGRES_DB=$POSTGRES_TEST_DB x.migrate down || true # nochange exits
 
-    local cache_opt="-count=1"
-    # we must only invalidate cache if database schema changes
-    cache_all "$GEN_CACHE/go-test.md5" .env.$X_ENV db/ && cache_opt=""
-
-    set -x
-    go_test -tags 'skip_xo' $cache_opt "$@" ./...
+    go_test -tags 'skip_xo' "$@" ./...
     # go_test -tags 'skip_xo,!skip_countone' "$@" -count=1 ./...
-    set +x
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
   xsetup.backup.cleanup
 }
 
-# Test frontend.
+# Test frontend. Accepts `vitest` parameters.
 # Args: [...]
 x.test.frontend() {
   # TODO accept vitest args
   config_template_setup frontend
 
   cd frontend
-  pnpm run test:no-watch
+  pnpm run test:no-watch "$@"
   # pnpm run test-types:no-watch
 }
 
-# Test frontend on file changes.
+# Test frontend on file changes. Accepts `vitest` parameters.
 # Args: [...]
 x.test.frontend.watch() {
   config_template_setup frontend
 
   cd frontend
-  pnpm run test
+  pnpm run test "$@"
 }
 
 # Run custom xo generation script tests. Accepts `go test` parameters.
@@ -1330,7 +1344,7 @@ test_backend_watch() {
       --format='%T %f' \
       --timefmt='%s' \
       . && clear &&
-      go_test -count=1 -tags $tags "$@" &&
+      go_test -tags $tags "$@" &&
       echo "${GREEN}✓ All tests passing${OFF}"
   done
 }
@@ -1402,7 +1416,7 @@ x.run.all() {
   run_hot_reload
 
   while true; do
-    sleep 1000
+    sleep 5
   done
 
   # TODO fix won't kill children
