Dev (#217)
* sqlc gen update

* fix crud gen

* implement access token flow for dev https - go.mod update

* dont show tracebacks on user cancelling commands

* update oidc mock server

* attempt to add users pagination endpoint

* paginated users and notes for openapi.yaml required rest schema gen

* use same pagination pattern as notifications

* notes for swaggest not handling array types and pagination

* dont auto redirect to oidc login and styles update

* update

* env update

* refactoring and extension update

* update mantine to latest version without breaking emotion

* updating mantine with autocompleted colors and no emotion type errors

* update

* mantine react table links

* skip e2e test

* refactor

* update

* get paginated users

* update

* orval react query client using shared options

* move form generation demo to own view

* golang custom postfix extension

* virtuoso placeholder

* working virtuoso alongside combobox

* attempt to use react query

* update

* move demo form initial values outside to prevent bad date error on hot reload

* debugging ifninite render

* fix bad cursor due to querykey slug

* show route links on home

* styyling user permissions

* working on dynamic cache tables creation and update in place of materialized views for proper multicolumn indexes and xo gen

* working on dynamic mat table creation

* important note for generated cache table triggers

* create cache table statemnt working

* pg_format refactor attempt

* update workspace config for pg format

* fix pg format palceholder regex

* lint and update config

* trying to ensure column names dont match in workitems and project tables in post migrations

* add column name check to prevent clashing in project work items

* notes for work item triggers

* postgres anon block snippet

* update

* updating

* updating

* update

* update

* update

* notes for mantine react table v2 filters

* update

* definitely fixed trigger for cache tables creation and update

* update

* test fix rate limt mw and checks

* really fix triggers - pending proper parametrizing

* add nullability to created cache schema table

* xo generates properly when there are no PKs - ie cache schema - update to pg16

* cleanup

* initial data with demo two cache

* generation notes

* refactor

* debug retries

* remove wi comment for later crud gen

* better random entities

* adding work item comments and updates for better fixture factories

* update work item comments test and generic crud templates

* fix crud gen reop templates

* frontend gen uses exploded spec due to js-lib not handling anchors

* internally handle error from test fixture factory

* tracing test

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -618,7 +618,8 @@ x.gen.sqlc() {
     rm -f "$PG_REPO_GEN"/db/*.sqlc.go
     x.lint.sql
     sqlc generate --experimental -f "$PG_REPO_DIR"/sqlc.yaml || err "Failed sqlc generation"
-    rm -f "$PG_REPO_GEN"/db/models.go # sqlc enums
+    rm -f "$PG_REPO_GEN"/db/models.go                            # sqlc enums
+    sed -i 's/\bdb DBTX\b/d DBTX/g' "$PG_REPO_GEN"/db/querier.go # consistent with repo gowrap gen so we can use reposwrappers
     gowrap gen \
       -g \
       -p "$GOMOD_PKG/$PG_REPO_GEN/db" \
@@ -652,9 +653,8 @@ x.gen.xo() {
       --ignore "*.updated_at" ||
       err "Failed xo extra_schema schema generation" &
 
-    rm -rf "$PG_REPO_GEN"/db/cache
-    mkdir -p "$PG_REPO_GEN"/db/cache
-    xo_schema -o "$PG_REPO_GEN"/db/cache \
+    mkdir -p "$PG_REPO_GEN"/db
+    xo_schema -o "$PG_REPO_GEN"/db \
       --schema cache ||
       err "Failed xo cache schema generation" &
 
@@ -865,19 +865,29 @@ x.gen.frontend() {
   { { {
     export PATH=frontend/node_modules/.bin:$PATH
 
-    SCHEMA_OUT="frontend/src/types/schema.d.ts"
-    orval_config="frontend/orval.config.ts"
+    local exploded_spec=openapi.exploded.yaml
 
-    cache_all "$CACHE/frontend.md5" bin/project bin/.helpers.sh .env.$X_ENV $SPEC_PATH $orval_config frontend/scripts/ frontend/package.json && return 0
+    SCHEMA_OUT="frontend/src/types/schema.d.ts"
+    local orval_config="frontend/orval.config.ts"
+    deps=(
+      "$orval_config"
+      "frontend/src/react-query.ts"
+      "frontend/scripts/"
+      "frontend/package.json"
+    )
+
+    cache_all "$CACHE/frontend.md5" bin/project bin/.helpers.sh .env.$X_ENV $SPEC_PATH ${deps[@]} && return 0
 
     config_template_setup frontend # no need to run if cached .env
 
     mkdir -p frontend/src/types
     rm -rf frontend/src/gen
 
+    yq 'explode(.)' $SPEC_PATH >$exploded_spec # js-lib won't support anchors - used by most gen libs
+
     {
       node frontend/scripts/generate-client-validator.js
-      # TODO allow custom validate.ts baked into fork
+      # client-validator will be useless with orval
       rm -f frontend/src/client-validator/gen/validate.ts
       find frontend/src/client-validator/gen/ -type f -exec \
         sed -i "s/from '.\/validate'/from '..\/validate'/g" {} \;
@@ -885,7 +895,7 @@ x.gen.frontend() {
 
     {
       v="$(openapi-typescript --version)"
-      openapi-typescript $SPEC_PATH --output "$SCHEMA_OUT" --path-params-as-types --prettier-config .prettierrc
+      openapi-typescript $exploded_spec --output "$SCHEMA_OUT" --path-params-as-types --prettier-config .prettierrc
       echo "/* Generated by openapi-typescript $v */
 /* eslint-disable @typescript-eslint/ban-ts-comment */
 /* eslint-disable */
@@ -1086,17 +1096,9 @@ x.lint.sql() {
       "db"
     )
     for slq_dir in ${SQL_DIRS[@]}; do
-      pg_format \
-        --spaces 2 \
-        --wrap-limit 130 \
-        --function-case 2 \
-        --keyword-case 1 \
-        --placeholder "sqlc\\.(arg|narg)\\(:?[^)]*\\)" \
-        --inplace \
-        --keep-newline \
-        --comma-start \
-        --nogrouping \
-        $(find "$slq_dir" -name '*.*sql')
+      # TODO:
+      # "pgFormatter.configFile": "./<...>", so we can use it in vscode settings too
+      pg_format --config .pg_format $(find "$slq_dir" -name '*.*sql')
     done
 
     echo "Success"
@@ -1260,7 +1262,7 @@ x.run.frontend() {
 }
 
 # Run all project services with hot reload enabled in dev mode.
-x.run-dev() {
+x.run.all() {
   run_hot_reload
 
   while true; do
@@ -1300,7 +1302,7 @@ x.run-dockerized() {
   run_shared_services up -d --build --wait
   x.db.recreate
 
-  x.gen
+  # x.gen
 
   setup_swagger_ui
 
@@ -1521,6 +1523,22 @@ x.dev-utils.create-crud-tests() {
   { { {
     load_exported_crud_gen_vars ${@}
 
+    local file="internal/repos/postgresql/new_random_test.go"
+    echo "
+func newRandom${pascal_name}(t *testing.T, d db.DBTX $create_params) *db.${pascal_name} {
+	t.Helper()
+
+	${camel_name}Repo := reposwrappers.New${pascal_name}WithRetry(postgresql.New${pascal_name}(), testutil.NewLogger(t), 3, 200*time.Millisecond)
+
+	cp := Random${pascal_name}CreateParams(t $create_args)
+
+	${camel_name}, err := ${camel_name}Repo.Create(context.Background(), d, cp)
+	require.NoError(t, err, \"failed to create random entity\") // IMPORTANT: must fail. If testing actual failures use random create params instead
+
+	return ${camel_name}
+}
+    " >>"$file" && gofumpt -w $file
+
     local file="internal/repos/postgresql/repo_${snake_name}_test.go"
     test -e "$file" && err "File $file exists. Please rename to avoid overwrite"
     bash "$BIN_TEMPLATES_DIR"/crud-repo-tests.go.tmpl.bash >"$file" && gofumpt -w $file
@@ -1530,6 +1548,7 @@ x.dev-utils.create-crud-tests() {
     local file="internal/rest/api_${snake_name}_test.go"
     test -e "$file" && err "File $file exists. Please rename to avoid overwrite"
     bash "$BIN_TEMPLATES_DIR"/crud-api-tests.go.tmpl.bash >"$file" && gofumpt -w $file
+
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -1878,6 +1897,8 @@ generate_structs_map() {
   # workaround for reflection type name with generics in swaggest
   ast-parser find-structs --create-generics-map --public-only "$path" >"internal/codegen/reflectTypeMap.gen.json"
 
+  # TODO: also need to include array of structs in models.go so that is_rest_type is true for oapi-codegen
+  # and we use existing rest types for arrays as well
   mapfile -t structs < <(ast-parser find-structs --exclude-generics --public-only "$path")
   go-utils.find_enums enums "$path"
   go-utils.find_all_types all_types "$path"
@@ -1942,7 +1963,7 @@ setup_swagger_ui() {
 
   local bundle_spec="$SWAGGER_UI_DIR/openapi.yaml"
   cp $SPEC_PATH $bundle_spec
-  yq 'explode(.)' -i $bundle_spec
+  yq 'explode(.)' -i $bundle_spec # derefence yaml
   sed -i 's/!!merge //' $bundle_spec
 }
 
@@ -2304,7 +2325,7 @@ if [[ -n "$1" ]]; then
       if [[ -n $X_IGNORE_BUILD_ERRORS ]]; then
         echo "${YELLOW}[WARNING] A rerun without ignoring build errors is required"
       fi
-      exit $?
+      exit $? # do not quote
     fi
   done
 fi
