Dev (#70)
* trim xo column comment annotations

* remove cache for jet - already super fast

* otel update

* sugared logger by default - desugar when perf matters

* some logging

* regen counterfeiter

* update initial data

* TODO fix M2M join when name clashes in members

* TODO fix scan to custom struct with m2m join extra fields

* adhoc fix for joins with m2m extra fields - need xo update

* refactor m2m join gen and better xo and sqlc cleanup

* TODO group by append joins

* update groupbys - pending o2o fix

* notes on fixing O2O join table missing roupbysource /home/daniel/Repos/github.com/danicc097/openapi-go-gin-postgres-sqlc/e2e/.venv/bin/activate

* fix xo groupby generation

* update xo test schema

* refactor gen backup and restore

* automatic change to git top level dir

* notes

* sleep before showing confirm prompt

* refactor and update stopship

* dedicated schema for xo tests to allow postgres_test db reuse

* update sql linting and xo schema

* updaet xo tests - broken

* dedicated tests for xo templates

* fix --x-help not showing command comments and update schema for xo tests

* split usage help parsing to file

* update gen lint

* TODO fix M2O generation of O2O

* TODO update xo gen to reflect current NotificationsBySender

* update go test xo test

* some updates

* almost fixed o2o from m2o gen

* update

* update

* fix xo gen

* add tables to xo tests and refactor

* notes on better inferred o2o when pk is fk

* cleanup

* access tables when generating constraints

* xo can generate O2O both sides automatically when PK is FK

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -10,7 +10,9 @@ export PROC=$$
 
 source ".helpers.sh"
 source ".project.dependencies.sh"
+source ".project.usage.sh"
 
+starting_cwd=$(pwd)
 ensure_pwd_is_top_level
 
 # log for any function output.
@@ -36,8 +38,6 @@ xlog() {
 
   local _=$(printf "%*s |\n" $((max_len + 1)) "$fname")
   sed -ue "s/^/${color}$fname >${OFF} /"
-
-  # return ${PIPESTATUS[0]}
 }
 
 # log stderr for any function output.
@@ -54,8 +54,6 @@ xerr() {
 
   local _=$(printf "%*s |\n" $((max_len + 1)) "$fname")
   sed -ue "s/^/${RED}$fname >${OFF} /" >&2
-
-  # return ${PIPESTATUS[0]}
 }
 
 kill_descendants() {
@@ -158,7 +156,7 @@ x.setup.swagger-ui() {
 
 # Run pre-generation scripts in the internal package.
 x.gen.pregen() {
-  cache-gen
+  backup-gen
   drop-and-migrate-gen-db
   { { {
     POSTGRES_DB="$GEN_POSTGRES_DB"
@@ -271,7 +269,7 @@ x.gen.pregen() {
 
     pregen -env=".env.$env" -op-id-auth="$OPID_AUTH"
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # for manually inserted elements via migrations, e.g. projects, kanban_steps, work_item_type,
@@ -380,7 +378,7 @@ clean_yq_array() {
 
 # Run post-generation scripts in the internal package.
 x.gen.postgen() {
-  cache-gen
+  backup-gen
   drop-and-migrate-gen-db
   { { {
     POSTGRES_DB="$GEN_POSTGRES_DB"
@@ -394,24 +392,25 @@ x.gen.postgen() {
 
     postgen -env=".env.$env"
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Generate type-safe Go code from SQL.
 x.gen.sqlc() {
-  cache-gen
+  backup-gen
   drop-and-migrate-gen-db
   { { {
     echo "Running generation"
+    rm -f "$PG_REPO_GEN"/db/*.sqlc.go
     sqlc generate --experimental -f "$PG_REPO_DIR"/sqlc.yaml || err "Failed sqlc generation"
-    rm "$PG_REPO_GEN"/db/models.go # sqlc enums
+    rm -f "$PG_REPO_GEN"/db/models.go # sqlc enums
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Automatically generate CRUD and index queries with joins based on existing indexes from a Postgres schema.
 x.gen.xo() {
-  cache-gen
+  backup-gen
   drop-and-migrate-gen-db
   { { {
     if md5sum -c "$CACHE/xo.md5" >/dev/null && [[ $FORCE_REGEN -eq 0 ]]; then
@@ -422,7 +421,7 @@ x.gen.xo() {
 
     echo "Running generation"
 
-    rm -rf "$PG_REPO_GEN"
+    rm -rf "$PG_REPO_GEN"/db/*.xo.go
 
     mkdir -p "$PG_REPO_GEN"/db
     xo_schema -o "$PG_REPO_GEN"/db --debug \
@@ -448,7 +447,7 @@ x.gen.xo() {
       -name "*.go")
     goimports -w $files
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Shows current database column comments used in xo codegen
@@ -477,20 +476,13 @@ WHERE a.attisdropped = false
 
 # Generate a type-safe SQL builder.
 x.gen.jet() {
-  cache-gen
+  backup-gen
   drop-and-migrate-gen-db
   { { {
     # results may be combined with xo's *Public structs and not reinvent the wheel for jet.
     # should not be hard to generate all adapters at once jet->xo *Public in a new file alongside jet gen.
     # in the end fields are the same name if goName conventions are followed (configurable via custom jet cmd)
     # if it gives problems for some fields (ID, API and the like)
-
-    if md5sum -c "$CACHE/jet.md5" >/dev/null && [[ $FORCE_REGEN -eq 0 ]]; then
-      echo "Skipping generation (cached). Force regen with --x-force-regen"
-      exit 0
-    fi
-    md5_all "$CACHE/jet.md5" ${CACHE_DEP_FILES[@]} go.mod db/ &
-
     echo "Running generation"
 
     local gen_path="$PG_REPO_GEN/jet"
@@ -502,12 +494,12 @@ x.gen.jet() {
       rm -r "./$gen_path/$GEN_POSTGRES_DB/"
     }
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Generate interface wrappers with common logic: tracing, timeout...
 x.gen.gowrap() {
-  cache-gen
+  backup-gen
   { { {
     if md5sum -c "$CACHE/gowrap.md5" >/dev/null && [[ $FORCE_REGEN -eq 0 ]]; then
       echo "Skipping generation (cached). Force regen with --x-force-regen"
@@ -545,7 +537,7 @@ x.gen.gowrap() {
 
     wait
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Generate Go client and server.
@@ -618,7 +610,7 @@ x.gen.proto() {
 
 # Run frontend code generation.
 x.gen.frontend() {
-  cache-gen
+  backup-gen
   { { {
     (
       frontend_config_setup
@@ -657,15 +649,17 @@ export type schemas = components['schemas']
       wait_without_error
     )
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Run all codegen and postgen commands for the project.
 x.gen() {
-  cache-gen # Modification of vars inside would be local to subshell (caused by pipeline)
+  backup-gen # Modification of vars inside would be local to subshell (caused by pipeline)
   drop-and-migrate-gen-db
   { { {
     echo "Running code generation"
+
+    x.lint.sql
 
     x.gen.build-tools # || true (this should not fail compilation anymore, the whole app should be compilable at this point)
 
@@ -677,11 +671,11 @@ x.gen() {
     x.gen.gowrap &
     x.gen.proto &
     x.gen.xo &
+    x.gen.sqlc &
     x.gen.jet &
 
     wait_without_error
 
-    x.gen.sqlc # with md5 cache, can't have xo and sqlc run at the same time, so let's have xo be responsible for rm dir
     x.gen.pregen
 
     x.gen.postgen &
@@ -701,7 +695,7 @@ x.gen() {
     x.gen.frontend
 
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Build code generation custom tools.
@@ -778,7 +772,6 @@ x.lint.sql() {
         --keep-newline \
         --comma-start \
         --nogrouping \
-        --comma-break \
         $(find "$slq_dir" -name '*.*sql')
     done
 
@@ -789,7 +782,7 @@ x.lint.sql() {
 # Run required backend pre-test setup: services, database cleanup, codegen...
 # Can be called independently, e.g. before running tests through an IDE.
 x.test.backend.setup() {
-  cache-gen # Modification of vars inside would be local to subshell (caused by pipeline)
+  backup-gen # Modification of vars inside would be local to subshell (caused by pipeline)
   { { {
     # NOTE: tests run independently in Go so we can't have a function be called and run
     # only once before any test starts
@@ -798,7 +791,7 @@ x.test.backend.setup() {
     # no need to migrate, done on every test run internally
     drop_and_recreate_db $POSTGRES_TEST_DB
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-  cache-gen.cleanup
+  backup-gen.cleanup
 }
 
 # Test backend. Accepts `go test` parameters.
@@ -808,6 +801,7 @@ x.test.backend() {
     x.test.xo
 
     export POSTGRES_TRACE=false
+    export GIN_MODE=release
     yes y 2>/dev/null | POSTGRES_DB=$POSTGRES_TEST_DB x.migrate down || true
     POSTGRES_DB=$POSTGRES_TEST_DB x.migrate up # for post-migration scripts
     echo "Running ${GREEN}\"APP_ENV=$env go test $* ./...\"${OFF}"
@@ -835,10 +829,10 @@ x.test.frontend.watch() {
 # Run custom xo generation script tests
 x.test.xo() {
   { { {
-    POSTGRES_DB="xo_tests"
+    POSTGRES_DB="$POSTGRES_TEST_DB"
     GEN_POSTGRES_DB="$POSTGRES_DB"
 
-    drop_and_recreate_db $POSTGRES_DB
+    drop_and_recreate_db $POSTGRES_DB # FIXME wrong gen when tables with equal names in public schema exist as well
 
     echo "Running xo template tests"
 
@@ -849,21 +843,25 @@ x.test.xo() {
     rm -rf "$test_dir/got"
     mkdir -p "$test_dir/got"
     xo_schema -o "$test_dir/got" --debug \
-      --schema public \
+      --schema xo_tests \
       --ignore "*.created_at" \
-      --ignore "*.updated_at" >/dev/null || err "Failed xo public schema generation"
+      --ignore "*.updated_at" >/dev/null || err "Failed xo xo_tests schema generation"
 
     files=$(find "$test_dir/got" \
       -name "*.go")
     goimports -w $files
     gofumpt -w $files
 
-    if ! $test_dir/run_tests; then
-      confirm "Do you want to update test snapshot with current changes?" </dev/tty >/dev/tty && {
-        rm -rf "$test_dir/want"
-        cp -r "$test_dir/got" "$test_dir/want"
+    APP_ENV="$env" go test "$GOMOD_PKG/internal/repos/postgresql/xo-templates/tests" ||
+      err "xo tests failed"
+
+    if ! $test_dir/diff_check; then
+      confirm "Do you want to update test snapshot with current changes?" </dev/tty >/dev/tty && { # must redirect inside xlog pipeline
+        rm -rf "$test_dir/snapshot"
+        cp -r "$test_dir/got" "$test_dir/snapshot"
       }
     fi
+
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -994,35 +992,10 @@ x.recreate-shared-services() {
 # - Magic keyword "STOPSHIP" not found in tracked files.
 x.release() {
   { { {
-    x.search-stopship "STOPSHIP" &
-    go mod verify &
+    search_stopship "STOPSHIP" &
+    # go mod verify & # TODO go.work issues solved in go 1.21 (https://github.com/golang/go/issues/54372)
 
-    wait
-  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
-}
-
-# Block build if magic keyword is found in any file
-# Args: keyword
-x.search-stopship() {
-  { { {
-    stopship_keyword="$1"
-    local matches
-    matches=$(find "$(git rev-parse --show-toplevel)" \
-      -type f \
-      -not -path '**/.git/*' \
-      -not -path '**/.venv/*' \
-      -not -path '**/node_modules/*' \
-      -not -path '**/build/*' \
-      -not -path '**/*.pyc' \
-      -not -path "$0" \
-      -not -exec git check-ignore -q --no-index {} \; \
-      -exec grep -i --files-with-matches --regexp="$stopship_keyword" {} \;)
-    if [[ -n $matches ]]; then
-      echo "${RED}'$stopship_keyword'${OFF} found in tracked files."
-      echo "Please fix all related issues in the following files:"
-      printf "\t %s\n" $matches
-      exit 1
-    fi
+    wait_without_error
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
@@ -1081,9 +1054,10 @@ x.db.psql() {
   docker exec -it postgres_db_"$PROJECT_PREFIX" psql -d $POSTGRES_DB
 }
 
-# psql session for the codegen specific database.
-x.db.psql-gen() {
-  docker exec -it postgres_db_"$PROJECT_PREFIX" psql -d $GEN_POSTGRES_DB
+# psql session for `database`.
+# Args: database
+x.db.psql-db() {
+  docker exec -it postgres_db_"$PROJECT_PREFIX" psql -d $1
 }
 
 # Show active and max number of connections for the current environment.
@@ -1552,39 +1526,39 @@ frontend_config_setup() {
 }
 
 # saves the current gen state to allow restoring in the event of early exit
-cache-gen() {
-  test -n "$restore_cache_caller" && return
+backup-gen() {
+  test -n "$backup_gen_caller" && return
 
-  restore_cache_caller="${FUNCNAME[1]}"
+  backup_gen_caller="${FUNCNAME[1]}"
 
-  rm -rf "$CACHE_GEN"
-  mkdir -p "$CACHE_GEN"
-  mkdir -p "$CACHE_FRONTEND_GEN"
-  mkdir -p "$CACHE_PG_REPO_GEN"
-  backup_gen_files internal "$CACHE_GEN"
+  rm -rf "$GEN_BACKUP"
+  mkdir -p "$GEN_BACKUP"
+  mkdir -p "$FRONTEND_GEN_BACKUP"
+  mkdir -p "$PG_REPO_GEN_BACKUP"
+  backup_gen_files internal "$GEN_BACKUP"
 
-  cp "$SPEC" "$CACHE_GEN"
-  rsync -a --delete "$FRONTEND_GEN/" "$CACHE_FRONTEND_GEN"
-  rsync -a --delete "$PG_REPO_GEN/" "$CACHE_PG_REPO_GEN"
+  cp "$SPEC" "$GEN_BACKUP"
+  rsync -a --delete "$FRONTEND_GEN/" "$FRONTEND_GEN_BACKUP"
+  rsync -a --delete "$PG_REPO_GEN/" "$PG_REPO_GEN_BACKUP"
 
   restore_cache=1
 }
 
-cache-gen.cleanup() {
-  if [[ "$restore_cache_caller" = "${FUNCNAME[1]}" ]]; then
+backup-gen.cleanup() {
+  if [[ "$backup_gen_caller" = "${FUNCNAME[1]}" ]]; then
     restore_cache=0
   fi
 }
 
-cache-gen.restore() {
+backup-gen.restore() {
   echo "Restoring previously generated code..."
   wait
-  mv "$CACHE_GEN/$SPEC" "$SPEC"
-  rsync -a --delete "$CACHE_PG_REPO_GEN/" "$PG_REPO_GEN/"
-  rsync -a --delete "$CACHE_FRONTEND_GEN/" "$FRONTEND_GEN/"
-  restore_gen_files "$CACHE_GEN" internal
+  mv "$GEN_BACKUP/$SPEC" "$SPEC"
+  rsync -a --delete "$PG_REPO_GEN_BACKUP/" "$PG_REPO_GEN/"
+  rsync -a --delete "$FRONTEND_GEN_BACKUP/" "$FRONTEND_GEN/"
+  restore_gen_files "$GEN_BACKUP" internal
 
-  rm "$CACHE_GEN"/*.md5 # clear gen cache
+  rm -f "$GEN_BACKUP"/*.md5 # clear gen cache
 }
 
 backup_gen_files() {
@@ -1604,145 +1578,6 @@ restore_gen_files() {
 
   # -C changes cwd to dir before extracting
   tar xzvf "$backup_dir/backup_gen_files.tar.gz" -C "$dest_dir" --overwrite --strip-components=1 &>/dev/null
-}
-
-usage() {
-  command_comments_parser() {
-    head -$((${lns[$i]} - 1)) $0 |
-      tac |
-      sed -n '/#/!q;p' |
-      tac |
-      awk '{$1=$1;print}'
-  }
-
-  command_options_comments_parser() {
-    tail -n +$((${lns[$i]} + 1)) $0 |
-      sed -n '/^[[:blank:]]*#/!q;p' |
-      awk '{$1=$1;print}'
-  }
-
-  construct_row() {
-    comment_parser="$1"
-    for i in ${!lns[@]}; do
-      comment_paragraph="$($comment_parser)"
-      ROWS["${rows[$i]}"]="$comment_paragraph"
-      mapfile -t comments <<<"${ROWS[${rows[$i]}]}"
-      # Parse # Args:
-      for comment in "${comments[@]}"; do
-        comment="$(clean_comment "$comment")"
-        args="-"
-        if [[ ${comment,,} == args:* ]]; then
-          args=$(clean_args "$comment")
-        fi
-        ROW_ARGS[${rows[$i]}]="$args"
-      done
-    done
-
-    for i in "${!rows[@]}"; do
-      mapfile -t comments <<<"${ROWS[${rows[$i]}]}"
-      for j in "${!comments[@]}"; do
-        comment="$(clean_comment "${comments[$j]}")"
-        if [[ ${comment,,} == args:* ]]; then
-          continue
-        fi
-
-        # if its the first doc line show all info
-        if [[ $j = 0 ]]; then
-          docs+=("$(
-            printf -- "%s\t%s\t%s" \
-              "${rows[$i]}" \
-              "${ROW_ARGS[${rows[$i]}]}" \
-              "$comment"
-          )")
-          continue
-        fi
-
-        # if its a remaining comment line
-        docs+=("$(
-          printf -- "%s\t%s\t%s" \
-            "" \
-            "" \
-            "$comment"
-        )")
-      done
-    done
-
-    column -t \
-      --separator $'\t' \
-      --output-width 150 \
-      --table-noextreme C2 \
-      --table-noheadings \
-      --table-wrap C3 \
-      --table-columns C1,C2,C3 < <(printf "    %s\n" "${docs[@]}")
-  }
-
-  declare -A ROWS ROW_ARGS
-  declare docs rows X_OPTIONS
-
-  for c in "${COMMANDS[@]}"; do
-    shopt -s extdebug
-    lns+=("$(declare -F x.$c | awk '{print $2}')")
-    rows+=("${c}")
-    shopt -u extdebug
-  done
-
-  x_functions="$(construct_row command_comments_parser)"
-
-  lns=()
-  rows=()
-  docs=()
-
-  parse_x_options X_OPTIONS
-
-  for c in "${X_OPTIONS[@]}"; do
-    lns+=("${c##*)}")
-    rows+=("${c%%)*}")
-  done
-
-  x_options="$(construct_row command_options_comments_parser)"
-
-  cat <<EOF
-
-$BOLD$UNDERSCORE$(basename $0)$OFF centralizes all relevant project commands.
-
-${BOLD}USAGE:
-    $RED$(basename $0) x.function [--x-option ...] args [optional args]$OFF
-
-${BOLD}x.functions:$OFF
-$(echo "${x_functions}" |
-    sed -E 's/    ([[:alnum:][:punct:]]*)(.*)/    '"$BLUE$BOLD"'\1'"$OFF"'\2''/')
-
-${BOLD}--x-options:$OFF
-$(echo "${x_options}" |
-      sed -E 's/    ([[:alnum:][:punct:]]*)(.*)/    '"$GREEN$BOLD"'\1'"$OFF"'\2''/')
-EOF
-
-}
-
-# gets all --x-options values
-parse_x_options() {
-  local -n __arr="$1" # pass ref by name
-  while IFS= read -r line; do
-    __arr+=("$(awk '{$1=$1;print $1 $NF}' <<<"$line")")
-  done < <(sed -nr '/.*(--x-[=*[:alnum:]_-]+[)]+).*/{p;=}' $0 | sed '{N;s/\n/ /}')
-  mapfile -t __arr < \
-    <(LC_COLLATE=C sort < <(printf "%s\n" "${__arr[@]}"))
-}
-
-clean_comment() {
-  tmp="$1"
-  tmp="${tmp//\#/}"
-  comment="${tmp#* }"
-  [[ -z $comment ]] && comment="·"
-  ((${#comment} > MAX_COMMENT_LEN)) && comment="${comment:0:MAX_COMMENT_LEN}..."
-  echo "$comment"
-}
-
-clean_args() {
-  tmp="$1"
-  tmp="${tmp,,##*args\:}"
-  args="${tmp#* }"
-  echo "$args"
 }
 
 ######################## ENTRYPOINT ########################
@@ -1884,9 +1719,9 @@ trap 'exit-cleanup $LINENO' 0 # EXIT (0) executed on exit from the shell
 
 exit-cleanup() {
   if [[ $restore_cache = 1 && -z $NO_CACHE ]]; then
-    cache-gen.restore #
+    backup-gen.restore #
   fi
-  cd "$TOP_LEVEL_DIR" || true
+  cd "$starting_cwd" || true
 }
 
 killgroup() {
@@ -1919,7 +1754,6 @@ readonly PG_REPO_DIR="$REPOS_DIR/postgresql"
 readonly XO_TEMPLATES_DIR="$PG_REPO_DIR/xo-templates"
 
 readonly POSTGRES_TEST_DB="postgres_test"
-readonly MAX_COMMENT_LEN=88
 readonly DUMPS_DIR="$HOME/openapi_go_gin_postgres_dumps"
 pkg="$(head -1 go.mod)"
 readonly GOMOD_PKG="${pkg#module *}"
@@ -1930,9 +1764,9 @@ readonly FRONTEND_GEN="$FRONTEND_SRC/gen"
 # common shared file dependencies for codegen checksums
 readonly CACHE_DEP_FILES=("bin/project bin/.helpers.sh .env.$env")
 readonly CACHE=".generate.cache"
-readonly CACHE_GEN="$CACHE/gen"
-readonly CACHE_PG_REPO_GEN="$CACHE_GEN/pgrepo/gen"
-readonly CACHE_FRONTEND_GEN="$CACHE_GEN/frontend/gen"
+readonly GEN_BACKUP="$CACHE/gen"
+readonly PG_REPO_GEN_BACKUP="$GEN_BACKUP/pgrepo/gen"
+readonly FRONTEND_GEN_BACKUP="$GEN_BACKUP/frontend/gen"
 
 readonly MAX_FNAME_LOG_LEN=13
 
@@ -1941,8 +1775,8 @@ GEN_POSTGRES_DB="gen_db"
 # determines if gen cache should be restore at program exit. 0|1
 restore_cache=0
 # stores the first executing function to track if caching gen is already running,
-# to allow for nested cache-gen and cache-cleanup inside multiple functions.
-restore_cache_caller=""
+# to allow for nested backup-gen and cache-cleanup inside multiple functions.
+backup_gen_caller=""
 
 # stores the first executing function to determine if a migration
 # is needed when running gen* functions which call each other
