oapi workaround - TODO enforce request names to be <opID>Request and figure out discriminators

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -728,21 +728,21 @@ x.gen.client-server() {
     echo "Running generation"
     paths=".openapi.paths.yaml"
 
+    local structs=()
+    mapfile -t structs < <(ast-parser find-structs --exclude-generics --public-only "internal/rest/models.go")
+    struct_names_list=$(join_by "," ${structs[*]})
+
     # hack to get separate types generation
     sed "s/\$ref: '\#\//\$ref: '$SPEC_PATH\#\//g" $SPEC_PATH >"$paths"
     # yq e 'del(.components)' -i "$paths" # dont delete since recent oapi-codegen does some checks even if we are not generating types
     go build -o $BUILD_DIR/oapi-codegen cmd/oapi-codegen/main.go || [[ -n "$X_IGNORE_BUILD_ERRORS" ]] # templates are embedded, required rebuild
 
     oapi-codegen --config internal/models/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed types generation"
-    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models "$paths" || err "Failed server generation"
+    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --structs "$struct_names_list" "$paths" || err "Failed server generation"
     oapi-codegen --config internal/client/oapi-codegen-client.yaml "$SPEC_PATH" || err "Failed client generation"
 
     codegen implement-server # based on oapi gen
 
-    local structs=()
-    mapfile -t structs < <(ast-parser find-structs --exclude-generics --public-only "internal/rest/models.go")
-    struct_names_list=$(join_by "," ${structs[*]})
-    echo struct_names_list: $struct_names_list
     files=$(find "internal/rest/" -name "*.go")
     goimports -w $files
     gofumpt -w $files
