full log function names for checks

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -12,7 +12,6 @@
 export PROC=$$
 
 source "${BASH_SOURCE%/*}/.helpers.sh"
-source "${BASH_SOURCE%/*}/.deps-check.sh"
 
 # FIXME m flag will prevent background process killing with ctrl-c
 set -Eeo pipefail
@@ -55,7 +54,6 @@ readonly PG_REPO="$REPOS/postgresql"
 readonly PG_REPO_GEN="$PG_REPO/gen"
 readonly POSTGRES_TEST_DB="postgres_test"
 readonly MAX_COMMENT_LEN=88
-readonly MAX_FNAME_LOG_LEN=13
 readonly DUMPS_FOLDER="$HOME/openapi_go_gin_postgres_dumps"
 readonly GEN_POSTGRES_DB="gen_db"
 pkg="$(head -1 go.mod)"
@@ -63,6 +61,7 @@ readonly GOMOD_PKG="${pkg#module *}"
 readonly OPID_AUTH="operationAuth.gen.json"
 readonly CACHE=".generate.cache"
 readonly CACHE_PG_REPO_GEN="$CACHE/gen"
+readonly MAX_FNAME_LOG_LEN=13
 
 restore_cache=0
 pids=""
@@ -72,13 +71,26 @@ dump_prefix="dump_${env}_"
 # log for any function output.
 xlog() {
   local fname="${FUNCNAME[1]#*.}"
+  local color="$BLUE"
+  local max_len=$MAX_FNAME_LOG_LEN
+
   [[ "$CMD" = "$fname" ]] && cat && return
-  if [[ ${#fname} -gt $MAX_FNAME_LOG_LEN ]]; then
-    fname="${fname:0:$MAX_FNAME_LOG_LEN}…"
+
+  if [[ "${FUNCNAME[1]%%.*}" != "x" ]]; then
+    fname="${FUNCNAME[1]}" # show non-x funcs
+    color="$MAGENTA"
   fi
 
-  local fn=$(printf "%*s |\n" $((MAX_FNAME_LOG_LEN + 1)) "$fname")
-  sed -ue "s/^/${BLUE}$fname >${OFF} /"
+  if [[ "${FUNCNAME[1]%%.*}" == "check" ]]; then
+    max_len=100
+  fi
+
+  if [[ ${#fname} -gt $max_len ]]; then
+    fname="${fname:0:$max_len}…"
+  fi
+
+  local fn=$(printf "%*s |\n" $((max_fname_log_len + 1)) "$fname")
+  sed -ue "s/^/${color}$fname >${OFF} /"
 }
 
 # log stderr for any function output.
@@ -87,11 +99,11 @@ xlog() {
 xerr() {
   local fname="${FUNCNAME[1]#*.}"
   [[ "$CMD" = "$fname" ]] && cat && return
-  if [[ ${#fname} -gt $MAX_FNAME_LOG_LEN ]]; then
-    fname="${fname:0:$MAX_FNAME_LOG_LEN}…"
+  if [[ ${#fname} -gt $max_fname_log_len ]]; then
+    fname="${fname:0:$max_fname_log_len}…"
   fi
 
-  local fn=$(printf "%*s |\n" $((MAX_FNAME_LOG_LEN + 1)) "$fname")
+  local fn=$(printf "%*s |\n" $((max_fname_log_len + 1)) "$fname")
   sed -ue "s/^/${RED}$fname >${OFF} /" >&2
 }
 
@@ -104,7 +116,27 @@ kill_descendants() {
 
 # Check build dependencies are met and prompt to install if missing.
 x.check-build-deps() {
-  check.all
+  { { {
+    mkdir -p ./bin/tools/
+
+    while IFS= read -r line; do
+      [[ $line =~ ^declare\ -f\ check\.bin\. ]] && BIN_CHECKS+=("${line##declare -f check.bin.}")
+      [[ $line =~ ^declare\ -f\ install\.bin\. ]] && BIN_INSTALLS+=("${line##declare -f install.bin.}")
+    done < <(declare -F)
+
+    for bin in "${BIN_CHECKS[@]}"; do
+      "check.bin.$bin" && continue
+
+      if ! element_in_array "$bin" "${BIN_INSTALLS[@]}"; then
+        exit 1
+      fi
+
+      confirm "Do you want to install $bin now?" || exit 1
+
+      echo "Installing $bin..."
+      "install.bin.$bin" || err "$bin installation failed"
+    done
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
 # Check dependencies and fetch required tools.
@@ -1023,6 +1055,257 @@ x.diff-oas() {
       echo "${RED}Breaking changes found in $SPEC${OFF}"
       return 1
     fi
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+########################### dependencies ###########################
+
+check.bin.bash() {
+  { { {
+    vers=${BASH_VERSION:0:1}
+    minver=4
+    { ((vers >= minver)) &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: $minver"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.column() {
+  { { {
+    local vers
+    vers=$(column --version)
+    minver="util-linux"
+    { [[ "$vers" = *$minver* ]] &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: $minver"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check.${OFF}"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.column() {
+  { { {
+    wget https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.2.tar.gz
+    tar -xf util-linux-2.36.2.tar.gz
+    cd util-linux-2.36.2 || exit 1
+    ./configure
+    make column
+    cp .libs/column ./bin/tools/
+    cd ..
+    rm -rf util-linux-2.*
+    column --version
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.protoc() {
+  { { {
+    local vers
+    vers=$(protoc --version)
+    minver="libprotoc 3"
+    { [[ "$vers" = *$minver* ]] &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: $minver"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.protoc() {
+  { { {
+    VERSION=3.19.4
+    id="protoc-$VERSION-linux-x86_64"
+    wget https://github.com/protocolbuffers/protobuf/releases/download/v"$VERSION"/$id.zip
+    unzip -q "$id".zip -d "$id"
+    mv "$id"/bin/protoc ./bin/tools/
+    rm -rf "$id"
+    rm -f "$id".zip
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.curl() {
+  { { {
+    local -a versa
+    mapfile versa < <(curl -V 2>&1)
+    { [[ "${versa[0]}" =~ ^.*(libcurl).* ]] &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. libcurl Required"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.go() {
+  { { {
+    local vers
+    vers=$(go version)
+    minver=18
+    { [[ "$vers" =~ ^[^\ ]+\ [^\ ]+\ go1\.([^\ \.]+) ]] &&
+      ((BASH_REMATCH[1] >= minver)) &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.docker() {
+  { { {
+    local vers
+    vers=$(docker --version)
+    minver=2
+    { [[ "$vers" =~ version[\ ]+([^\ \.]+) ]] &&
+      ((BASH_REMATCH[1] >= minver)) &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.docker-compose() {
+  { { {
+    local vers
+    vers=$(docker compose version)
+    minver=2
+    {
+      [[ "$vers" =~ [\ ]+[v]?([0-9]+)[\.]{1} ]] &&
+        ((BASH_REMATCH[1] >= minver)) &&
+        printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"
+    } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.pg_format() {
+  { { {
+    local vers
+    vers=$(pg_format --version)
+    minver=5
+    {
+      [[ "$vers" =~ [\ ]+([0-9]+)[\.]{1} ]] &&
+        ((BASH_REMATCH[1] >= minver)) &&
+        printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"
+    } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.pg_format() {
+  { { {
+    sudo apt-get install pgformatter
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.parallel() {
+  { { {
+    local vers
+    vers=$(parallel --version)
+    {
+      [[ "$vers" =~ (GNU parallel )([0-9]+) ]] &&
+        printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[2]}"
+    } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. Check install-parallel.sh"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.parallel() {
+  { { {
+    sudo apt-get install parallel
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.direnv() {
+  { { {
+    local vers
+    vers=$(direnv --version)
+    minver=2
+    { [[ "$vers" =~ ([0-9]+)[\.]{1} ]] &&
+      ((BASH_REMATCH[1] >= minver)) &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.direnv() {
+  { { {
+    sudo apt-get install direnv
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.sponge() {
+  { { {
+    { [[ $(command -v sponge) =~ /sponge$ ]] &&
+      printf "%s ✅\n" "${FUNCNAME[0]##*.}"; } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check."
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.sponge() {
+  { { {
+    sudo apt-get install moreutils
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+check.bin.mkcert() {
+  { { {
+    local vers
+    vers=$(mkcert --version)
+    minver=1
+    {
+      [[ "$vers" =~ [v]?([0-9]+)[\.]{1} ]] &&
+        ((BASH_REMATCH[1] >= minver)) &&
+        printf "%s ✅\n" "${FUNCNAME[0]##*.}: ${BASH_REMATCH[1]}"
+    } ||
+      {
+        echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
+        echo "Current version: $vers"
+        return 1
+      }
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+install.bin.mkcert() {
+  { { {
+    VERSION="1.4.3"
+    sudo apt-get install libnss3-tools
+    wget https://github.com/FiloSottile/mkcert/releases/download/v"$VERSION"/mkcert-v"$VERSION"-linux-amd64 -O mkcert
+    chmod +x mkcert
+    mv mkcert ./bin/tools/
+    cd certificates || exit
+    echo "Setting up local certificates"
+    mkcert --cert-file localhost.pem --key-file localhost-key.pem localhost "*.dev.localhost" "*.ci.localhost" "*.prod.localhost" 127.0.0.1 ::1 host.docker.internal
+    cd ..
+    mkcert -install
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
