add find all types to ast-parser and deprecation notices

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -727,29 +727,23 @@ x.gen.gowrap() {
 x.gen.client-server() {
   { { {
     echo "Running generation"
-    paths=".openapi.paths.yaml"
+    paths_file=".openapi.paths.yaml"
 
     local all_types=()
-    go-utils.find_all_types all_types "internal/rest/models.go"
+    mapfile -t all_types < <(ast-parser find-types --exclude-generics --public-only "internal/rest/models.go")
     all_types_list=$(join_by "," ${all_types[*]})
-    local models_structs=()
 
-    mapfile -t models_structs < <(ast-parser find-structs --exclude-generics --public-only "internal/rest/models.go")
-
-    struct_names_list=$(join_by "," ${all_types_list[*]})
-    echo $all_types_list
+    types_list=$(join_by "," ${all_types[*]})
     # hack to get separate types generation
-    sed "s/\$ref: '\#\//\$ref: '$SPEC_PATH\#\//g" $SPEC_PATH >"$paths"
-    # yq e 'del(.components)' -i "$paths" # dont delete since recent oapi-codegen does some checks even if we are not generating types
+    sed "s/\$ref: '\#\//\$ref: '$SPEC_PATH\#\//g" $SPEC_PATH >"$paths_file"
+    # yq e 'del(.components)' -i "$paths_file" # dont delete since recent oapi-codegen does some checks even if we are not generating types
     go build -o $BUILD_DIR/oapi-codegen cmd/oapi-codegen/main.go || [[ -n "$X_IGNORE_BUILD_ERRORS" ]] # templates are embedded, required rebuild
 
-    # TODO: generate types in rest package too, but will `ast-parse delete-duplicate-types internal/rest/openapi_types.gen.go`
-    # the other generated types in models pkg will be used in services, repos, db, but rest must use these generated types from rest package only
-    # (should enforce it by verifying import list in the package via ast-parser Imports map[string]*packages.Package):
-    # `ast-parser verify-no-import --imports "$GOMOD_PKG/internal/models" internal/rest` errors out if found
+    # Generated types in models pkg will be used in services, repos, db, but rest package must use original
+    # models from rest/models.go (source of generated spec schemas)
+    # and not the generated ones to avoid (a lot of) unnecessary conversions.
     oapi-codegen --config internal/models/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed types generation"
-    # oapi-codegen --config internal/rest/oapi-codegen-types.yaml "$SPEC_PATH" || err "Failed rest types generation"
-    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --types "$struct_names_list" "$paths" || err "Failed server generation"
+    oapi-codegen --config internal/rest/oapi-codegen-server.yaml --models-pkg models --types "$types_list" "$paths_file" || err "Failed server generation"
     oapi-codegen --config internal/rest/oapi-codegen-test-client.yaml "$SPEC_PATH" || err "Failed client generation"
     oapi-codegen --config internal/client/oapi-codegen-client.yaml "$SPEC_PATH" || err "Failed client generation"
 
