attempt to fix check deps

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -17,7 +17,13 @@ source "${BASH_SOURCE%/*}/.helpers.sh"
 set -Eeo pipefail
 set -o errtrace # TODO https://mywiki.wooledge.org/BashFAQ/105
 
-trap 'echo "ERR trap called in ${FUNCNAME-main context}."' ERR
+SCRIPT="$(basename $0)"
+
+# trap 'err_handler $LINENO' ERR
+
+err_handler() {
+  echo "ERR trap called in ${FUNCNAME-main context} from ${RED}$SCRIPT:$1${OFF}"
+}
 
 trap killgroup SIGINT
 
@@ -112,32 +118,6 @@ kill_descendants() {
   kill $pids || true
   kill "$(list_descendants $pids)" || true
   pids=""
-}
-
-# Check build dependencies are met and prompt to install if missing.
-x.check-build-deps() {
-  { { {
-    mkdir -p ./bin/tools/
-
-    while IFS= read -r line; do
-      [[ $line =~ ^declare\ -f\ check\.bin\. ]] && BIN_CHECKS+=("${line##declare -f check.bin.}")
-      [[ $line =~ ^declare\ -f\ install\.bin\. ]] && BIN_INSTALLS+=("${line##declare -f install.bin.}")
-    done < <(declare -F)
-
-    for bin in "${BIN_CHECKS[@]}"; do
-      "check.bin.$bin" && continue
-
-      if ! element_in_array "$bin" "${BIN_INSTALLS[@]}"; then
-        echo "Please install $bin manually and retry"
-        exit 1
-      fi
-
-      confirm "Do you want to install $bin now?" || exit 1
-
-      echo "Installing $bin..."
-      "install.bin.$bin" || err "$bin installation failed"
-    done
-  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
 # Check dependencies and fetch required tools.
@@ -1061,7 +1041,40 @@ x.diff-oas() {
 
 ########################### dependencies ###########################
 
+# Check build dependencies are met and prompt to install if missing.
+x.check-build-deps() {
+  { { {
+    mkdir -p ./bin/tools/
+
+    while IFS= read -r line; do
+      [[ $line =~ ^declare\ -f\ check\.bin\. ]] && BIN_CHECKS+=("${line##declare -f check.bin.}")
+      [[ $line =~ ^declare\ -f\ install\.bin\. ]] && BIN_INSTALLS+=("${line##declare -f install.bin.}")
+    done < <(declare -F)
+
+    echo "Checking dependencies..."
+    for bin in "${BIN_CHECKS[@]}"; do
+      local r
+      r="$(check.bin.$bin | tee /dev/tty)" # redirect to var while also streaming unbuffered output
+
+      if [[ ! "$r" =~ "Failed $bin check." ]]; then
+        continue
+      fi
+
+      if ! element_in_array "$bin" "${BIN_INSTALLS[@]}"; then
+        echo "No automatic installation available. Please install $bin manually and retry"
+        exit 1
+      fi
+
+      confirm "Do you want to install $bin now?" || exit 1
+
+      echo "Installing $bin..."
+      "install.bin.$bin" || err "$bin installation failed"
+    done
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
 check.bin.bash() {
+  # echo "pipestatus: ${PIPESTATUS[*]}"
   { { {
     vers=${BASH_VERSION:0:1}
     minver=4
@@ -1070,9 +1083,10 @@ check.bin.bash() {
       {
         echo "${RED}Failed ${FUNCNAME[0]##*.} check. (minimum version: $minver)${OFF}"
         echo "Current version: $vers"
-        return 1
+        exit 1
       }
   } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+  # echo "pipestatus exit: ${PIPESTATUS[*]}"
 }
 
 check.bin.column() {
