Dev (#154)
* remove workitem member shared service

* use repo for tag assign and removal

* merge main

* build version from commit

* refactor and assign tag fixes

* update

* fix useless logic

* merge

* remove useless join

* notes on ui settings storage

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -12,6 +12,7 @@ starting_cwd=$(pwd)
 ensure_pwd_is_top_level
 
 declare X_IGNORE_BUILD_ERRORS X_FORCE_REGEN X_NO_CONFIRMATION X_NO_GEN X_NO_CACHE X_ENV
+declare BUILD_VERSION
 
 readonly CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
@@ -1874,6 +1875,8 @@ for arg in ${args[@]}; do
   set -- "$@" "$arg"
 done
 
+export BUILD_VERSION="$X_ENV-$(git rev-parse --verify HEAD)"
+
 readonly X_IGNORE_BUILD_ERRORS X_FORCE_REGEN X_NO_CONFIRMATION X_NO_GEN X_NO_CACHE X_ENV
 
 ######################## INIT ########################
@@ -1908,8 +1911,8 @@ exit-cleanup() {
   fi
 
   rm -f backup-gen-stash-dummy.txt
-  git checkout "$CURRENT_BRANCH" >/dev/null || err "Could not checkout $CURRENT_BRANCH branch"
-  git branch -D "$gen_backup_branch" >/dev/null || true
+  git checkout "$CURRENT_BRANCH" &>/dev/null || err "Could not checkout $CURRENT_BRANCH branch"
+  git branch -D "$gen_backup_branch" &>/dev/null || true
   cd "$starting_cwd" || true
 
 }
