traefik update and move certificate creation to traefik setup

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -1008,13 +1008,36 @@ x.dev-utils.api-keys() {
 # Setups a traefik container with predefined configuration in `install-dir`.
 # Args: install-dir
 x.setup.traefik() {
-  git clone --depth=1 https://github.com/danicc097/traefik-bootstrap.git "$1"
-  docker network create traefik-net || true
-  mkdir -p "$1"/traefik/certificates
-  cp $CERTIFICATES_DIR/* "$1"/traefik/certificates
-  cd "$1" || exit
-  ./compose-up
-  cd - >/dev/null || exit
+  { { {
+    test -z "$1" && err "installation directory is required"
+
+    x.setup.mkcert
+
+    git clone --depth=1 https://github.com/danicc097/traefik-bootstrap.git "$1"
+    docker network create traefik-net || true
+    mkdir -p "$1"/traefik/certificates
+    cp $CERTIFICATES_DIR/* "$1"/traefik/certificates
+    cd "$1" || exit
+    cp traefik/dynamic_conf.yaml.example traefik/dynamic_conf.yaml
+    echo "Adding $PWD/certificates/"
+    yq e ".tls.certificates += [{
+    \"certFile\": \"$PWD/$CERTIFICATES_DIR/localhost.pem\",
+    \"keyFile\": \"$PWD/$CERTIFICATES_DIR/localhost-key.pem\"
+  }]" -i traefik/dynamic_conf.yaml
+
+    ./compose-up
+    cd - >/dev/null || exit
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
+}
+
+# Installs mkcert local development certificates.
+x.setup.mkcert() {
+  { { {
+    cd "$CERTIFICATES_DIR" || exit
+    echo "Setting up local certificates"
+    mkcert --cert-file localhost.pem --key-file localhost-key.pem "localhost" "*.e2e.localhost" "*.local.localhost" "*.dev.localhost" "*.ci.localhost" "*.prod.localhost" "127.0.0.1" "::1" "host.docker.internal"
+    cd -
+  } 2>&4 | xlog >&3; } 4>&1 | xerr >&3; } 3>&1
 }
 
 ########################## migrations ##########################
