Dev (#253)
* rename workitem assigned users

* m2m extra cols xo rename

* add ripgrep to bin dep check

* update

* remove npm dependabot

* gowork off in sync

* xo and sqlc at once

* lint error

* update - pending m2o join pgx row reading

* FIXME m2o not using json

* FIXME m2o must use m2m

* use proper array_agg for m2o xo

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -213,7 +213,7 @@ x.check-build-deps() {
       [[ $line =~ ^declare\ -f\ install\.bin\. ]] && BIN_INSTALLS+=("${line##declare -f install.bin.}")
     done < <(declare -F)
 
-    echo "Checking dependencies..."
+    echo "Checking dependency minimum versions..."
     for bin in "${BIN_CHECKS[@]}"; do
       # local r
       # r="$(...)" # redirect to var while also streaming unbuffered output with | tee /dev/tty
@@ -982,7 +982,7 @@ export type schemas = components['schemas']
 
     {
       orval --config $orval_config
-      orval_branded_types
+      orval_frontend_branded_types
     } &
 
     wait_without_error || err Failed jobs
@@ -1026,8 +1026,7 @@ x.gen() {
     x.gen.gowrap &
     x.gen.proto &
     # might be race between xo and sqlc
-    { retry 5 x.gen.xo; } &
-    { retry 5 x.gen.sqlc; } &
+    { x.gen.xo && x.gen.sqlc; } &
     x.gen.jet &
     generate_repo_constructor &
 
@@ -1101,8 +1100,8 @@ x.lint.go() {
     -not -path "**/*.gen.*" \
     -not -path "**/*.xo.go" \
     -name "*.go")
-  goimports -w $files || echo "Linting failed"
-  gofumpt -w $files || echo "Linting failed"
+  goimports -w $files || err "Linting failed"
+  gofumpt -w $files || err "Linting failed"
   golangci-lint run --config=.golangci.yml --allow-parallel-runners --fix &>/dev/null || true
 }
 
@@ -1429,8 +1428,8 @@ x.run.all() {
 
 # Syncs backend dependencies.
 x.backend.sync-deps() {
-  go mod tidy
-  go mod vendor
+  GOWORK=off go mod tidy
+  GOWORK=off go mod vendor
 }
 
 # Run project in production mode, i.e. dockerized and bundled.
@@ -1487,7 +1486,7 @@ x.backend.typecheck() {
 }
 
 # depends on gen.xo output
-orval_branded_types() {
+orval_frontend_branded_types() {
   local import_string="import type * as EntityIDs from 'src/gen/entity-ids'"
   local escaped_import_string=$(escape_sed "$import_string")
 
